version: '3'

services:
 api:
     build: .
     ports: 
     - 8000:8000
     volumes: 
     - .:/web
     depends_on:
     - db
 db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: library
      MYSQL_USER: venom
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/library
    ports:
      - "3306:3306"

volumes:
  db_data:




